# Generated by Django 4.2.8 on 2023-12-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('adress', models.CharField(max_length=50, verbose_name='Адрес')),
            ],
        ),
        migrations.RenameField(
            model_name='products',
            old_name='image_source',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Цена товара'),
        ),
    ]
